version: '3.8'

services:
  undc-microservicio:
    image: victorcuaresma/undc-microservicio:3.0
    container_name: undc-microservicio
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
